services:
  log_aggregator_dev:
    build: .
    profiles:
      - dev
    ports:
      - "8888:8888/udp"
    volumes:
      - ./config/dev_config.json:/app/config/config.json
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27016:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    profiles:
      - dev
  log_aggregator:
    image: ghcr.io/rainbowdashlabs/log-aggregator
    profiles:
      - prod
